openapi: 3.2.0
info:
  title: 10DLC Campaigns API
  description: This Service enables the Enterprise Customer to Addition/Deletion of the 10DLC number and Number Pool
  version: '2.3'
servers:
- url: https://api.syniverse.com
  description: Syniverse API
security:
- SyniverseToken: []
tags:
- name: Campaigns
paths:
  /engage/tendlc-services/v2/campaigns:
    get:
      tags:
      - Campaigns
      summary: Get multiple campaigns
      description: Get campaigns
      operationId: getCampaigns
      parameters:
      - name: page
        in: query
        description: Page number, begins from 0, default = 0
        required: false
        schema:
          type: string
          default: '0'
        example: 0
      - name: size
        in: query
        description: Size items on page, default = 10
        required: false
        schema:
          type: string
          default: '10'
        example: 10
      responses:
        '200':
          description: Request received
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiOkPageCampaignResponseExample'
        '401':
          description: You are not authorized to view the resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiUnauthorizedResponse'
        '409':
          description: Request already completed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiProcessedAlreadyResponse'
        '422':
          description: Unsupported Event Type Received
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiUnsupportedEventResponse'
  /engage/tendlc-services/v2/campaigns/{campaignId}:
    get:
      tags:
      - Campaigns
      summary: Get campaign by ID
      description: Get campaign details
      operationId: getCampaign
      parameters:
      - name: campaignId
        in: path
        description: Campaign Id
        required: true
        schema:
          type: string
          default: Id
        example: Id
      responses:
        '200':
          description: Request received
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiOkCampaignResponseExample'
        '401':
          description: You are not authorized to view the resource
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiUnauthorizedResponse'
        '404':
          description: Campaign Id does not exist
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiNotFoundResponse'
  /engage/tendlc-services/v2/campaigns/{campaignId}/suspend:
    post:
      tags:
      - Campaigns
      summary: Suspending deployed campaign
      description: Customer can suspend the deployed campaign
      operationId: suspendCampaign
      parameters:
      - name: campaignId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Request received
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiGeneralResponse'
        '202':
          description: Request already in Progress.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiAcceptedResponse'
        '400':
          description: '[Suspend operation is not allowed as campaign is already removed,Campaign suspend duplicate request,Campaign Deployed request in progress. Please retry after some time,Campaign remove request in progress,Suspend operation is not allowed as campaign is being removed,Campaign is not Deployed. Please retry after some time]'
          content:
            application/json:
              examples:
                CAMPAIGN_ALREADY_REMOVED:
                  description: CAMPAIGN_ALREADY_REMOVED
                  value:
                    code: 400
                    message: Suspend operation is not allowed as campaign is already removed
                    status: BAD_REQUEST
                    timestamp: 06-07-2022 01:53:10
                    data: {}
                CAMPAIGN_PENDING:
                  description: CAMPAIGN_PENDING
                  value:
                    code: 400
                    message: Campaign Deployed request in progress. Please retry after some time
                    status: BAD_REQUEST
                    timestamp: 06-07-2022 01:53:10
                    data: {}
                CAMPAIGN_REMOVAL_PROGRESS:
                  description: CAMPAIGN_REMOVAL_PROGRESS
                  value:
                    code: 400
                    message: Campaign remove request in progress
                    status: BAD_REQUEST
                    timestamp: 06-07-2022 01:53:10
                    data: {}
                CAMPAIGN_REMOVED_FAILED:
                  description: CAMPAIGN_REMOVED_FAILED
                  value:
                    code: 400
                    message: Suspend operation is not allowed as campaign is being removed
                    status: BAD_REQUEST
                    timestamp: 06-07-2022 01:53:10
                    data: {}
                CAMPAIGN_DEPLOY_FAILED:
                  description: CAMPAIGN_DEPLOY_FAILED
                  value:
                    code: 400
                    message: Campaign is not Deployed. Please retry after some time
                    status: BAD_REQUEST
                    timestamp: 06-07-2022 01:53:10
                    data: {}
                CAMPAIGN_DOES_NOT_EXIST:
                  description: CAMPAIGN_DOES_NOT_EXIST
                  value:
                    code: 400
                    message: Campaign does not exist
                    status: BAD_REQUEST
                    timestamp: 06-07-2022 01:53:10
                    data: {}
        '401':
          description: You are not authorized to view the resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiUnauthorizedResponse'
        '409':
          description: '[Campaign suspend duplicate request]'
          content:
            application/json:
              examples:
                CAMPAIGN_SUSPEND_DUPLICATE:
                  description: CAMPAIGN_SUSPEND_DUPLICATE
                  value:
                    code: 400
                    message: Campaign suspend duplicate request
                    status: BAD_REQUEST
                    timestamp: 06-07-2022 01:53:10
                    data: {}
        '500':
          description: Internal Error Occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiInternalErrorResponse'
  /engage/tendlc-services/v2/campaigns/{campaignId}/resume:
    post:
      tags:
      - Campaigns
      summary: Resuming suspended campaign
      description: Customer can resume the suspended campaign
      operationId: resumeCampaign
      parameters:
      - name: campaignId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Request received
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiGeneralResponse'
        '202':
          description: Request already in Progress.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiAcceptedResponse'
        '400':
          description: '[Resume operation is not allowed as campaign is already removed,Campaign does not exist,Campaign Deployed request in progress .,Campaign resume request is invalid, Campaign remove request in progress,Campaign resume request is invalid, Campaign remove request in progress,Campaign resume request is invalid, Campaign Deployed request in progress,Suspend Request Already in progress,Campaign resume request is invalid, the Campaign is already in deployed state]'
          content:
            application/json:
              examples:
                CAMPAIGN_ALREADY_REMOVED_RESUME:
                  description: CAMPAIGN_ALREADY_REMOVED_RESUME
                  value:
                    code: 400
                    message: Resume operation is not allowed as campaign is already removed
                    status: BAD_REQUEST
                    timestamp: 06-07-2022 01:53:10
                    data: {}
                CAMPAIGN_NOT_DEPLOYED:
                  description: CAMPAIGN_NOT_DEPLOYED
                  value:
                    code: 400
                    message: Campaign does not exist
                    status: BAD_REQUEST
                    timestamp: 06-07-2022 01:53:10
                    data: {}
                CAMPAIGN_PENDING_RESUME:
                  description: CAMPAIGN_PENDING_RESUME
                  value:
                    code: 400
                    message: Campaign Deployed request in progress .
                    status: BAD_REQUEST
                    timestamp: 06-07-2022 01:53:10
                    data: {}
                CAMPAIGN_REMOVAL_PROGRESS_RESUME:
                  description: CAMPAIGN_REMOVAL_PROGRESS_RESUME
                  value:
                    code: 400
                    message: Campaign resume request is invalid, Campaign remove request in progress
                    status: BAD_REQUEST
                    timestamp: 06-07-2022 01:53:10
                    data: {}
                CAMPAIGN_REMOVED_FAILED_RESUME:
                  description: CAMPAIGN_REMOVED_FAILED_RESUME
                  value:
                    code: 400
                    message: Campaign resume request is invalid, Campaign remove request in progress
                    status: BAD_REQUEST
                    timestamp: 06-07-2022 01:53:10
                    data: {}
                CAMPAIGN_DEPLOY_FAILED_RESUME:
                  description: CAMPAIGN_DEPLOY_FAILED_RESUME
                  value:
                    code: 400
                    message: Campaign resume request is invalid, Campaign Deployed request in progress
                    status: BAD_REQUEST
                    timestamp: 06-07-2022 01:53:10
                    data: {}
                CAMPAIGN_SUSPEND_IN_PROGRESS:
                  description: CAMPAIGN_SUSPEND_IN_PROGRESS
                  value:
                    code: 400
                    message: Suspend Request Already in progress
                    status: BAD_REQUEST
                    timestamp: 06-07-2022 01:53:10
                    data: {}
                CAMPAIGN_ALREADY_DEPLOYED:
                  description: CAMPAIGN_ALREADY_DEPLOYED
                  value:
                    code: 400
                    message: Campaign resume request is invalid, the Campaign is already in deployed state
                    status: BAD_REQUEST
                    timestamp: 06-07-2022 01:53:10
                    data: {}
        '401':
          description: You are not authorized to view the resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiUnauthorizedResponse'
        '409':
          description: Request already completed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiProcessedAlreadyResponse'
        '500':
          description: Internal Error Occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiInternalErrorResponse'
components:
  schemas:
    ApiUnsupportedEventResponse:
      type: object
      properties:
        code:
          type: integer
          description: Http status code
          format: int32
          example: 422
        message:
          type: string
          description: Message
          example: Unsupport Event Type Recieved
        status:
          type: string
          description: Http status
          example: Unprocessable Entity
          enum:
          - 100 CONTINUE
          - 101 SWITCHING_PROTOCOLS
          - 102 PROCESSING
          - 103 CHECKPOINT
          - 200 OK
          - 201 CREATED
          - 202 ACCEPTED
          - 203 NON_AUTHORITATIVE_INFORMATION
          - 204 NO_CONTENT
          - 205 RESET_CONTENT
          - 206 PARTIAL_CONTENT
          - 207 MULTI_STATUS
          - 208 ALREADY_REPORTED
          - 226 IM_USED
          - 300 MULTIPLE_CHOICES
          - 301 MOVED_PERMANENTLY
          - 302 FOUND
          - 302 MOVED_TEMPORARILY
          - 303 SEE_OTHER
          - 304 NOT_MODIFIED
          - 305 USE_PROXY
          - 307 TEMPORARY_REDIRECT
          - 308 PERMANENT_REDIRECT
          - 400 BAD_REQUEST
          - 401 UNAUTHORIZED
          - 402 PAYMENT_REQUIRED
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 405 METHOD_NOT_ALLOWED
          - 406 NOT_ACCEPTABLE
          - 407 PROXY_AUTHENTICATION_REQUIRED
          - 408 REQUEST_TIMEOUT
          - 409 CONFLICT
          - 410 GONE
          - 411 LENGTH_REQUIRED
          - 412 PRECONDITION_FAILED
          - 413 PAYLOAD_TOO_LARGE
          - 413 REQUEST_ENTITY_TOO_LARGE
          - 414 URI_TOO_LONG
          - 414 REQUEST_URI_TOO_LONG
          - 415 UNSUPPORTED_MEDIA_TYPE
          - 416 REQUESTED_RANGE_NOT_SATISFIABLE
          - 417 EXPECTATION_FAILED
          - 418 I_AM_A_TEAPOT
          - 419 INSUFFICIENT_SPACE_ON_RESOURCE
          - 420 METHOD_FAILURE
          - 421 DESTINATION_LOCKED
          - 422 UNPROCESSABLE_ENTITY
          - 423 LOCKED
          - 424 FAILED_DEPENDENCY
          - 425 TOO_EARLY
          - 426 UPGRADE_REQUIRED
          - 428 PRECONDITION_REQUIRED
          - 429 TOO_MANY_REQUESTS
          - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
          - 451 UNAVAILABLE_FOR_LEGAL_REASONS
          - 500 INTERNAL_SERVER_ERROR
          - 501 NOT_IMPLEMENTED
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          - 504 GATEWAY_TIMEOUT
          - 505 HTTP_VERSION_NOT_SUPPORTED
          - 506 VARIANT_ALSO_NEGOTIATES
          - 507 INSUFFICIENT_STORAGE
          - 508 LOOP_DETECTED
          - 509 BANDWIDTH_LIMIT_EXCEEDED
          - 510 NOT_EXTENDED
          - 511 NETWORK_AUTHENTICATION_REQUIRED
        timestamp:
          type: string
          description: Response time
          format: date-time
        data:
          type: object
          description: Response data
    ApiNotFoundResponse:
      type: object
      properties:
        code:
          type: integer
          description: Http status code
          format: int32
          example: 404
        message:
          type: string
          description: Message
          example: Campaign Id does not exist
        status:
          type: string
          description: Http status
          example: Not found
          enum:
          - 100 CONTINUE
          - 101 SWITCHING_PROTOCOLS
          - 102 PROCESSING
          - 103 CHECKPOINT
          - 200 OK
          - 201 CREATED
          - 202 ACCEPTED
          - 203 NON_AUTHORITATIVE_INFORMATION
          - 204 NO_CONTENT
          - 205 RESET_CONTENT
          - 206 PARTIAL_CONTENT
          - 207 MULTI_STATUS
          - 208 ALREADY_REPORTED
          - 226 IM_USED
          - 300 MULTIPLE_CHOICES
          - 301 MOVED_PERMANENTLY
          - 302 FOUND
          - 302 MOVED_TEMPORARILY
          - 303 SEE_OTHER
          - 304 NOT_MODIFIED
          - 305 USE_PROXY
          - 307 TEMPORARY_REDIRECT
          - 308 PERMANENT_REDIRECT
          - 400 BAD_REQUEST
          - 401 UNAUTHORIZED
          - 402 PAYMENT_REQUIRED
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 405 METHOD_NOT_ALLOWED
          - 406 NOT_ACCEPTABLE
          - 407 PROXY_AUTHENTICATION_REQUIRED
          - 408 REQUEST_TIMEOUT
          - 409 CONFLICT
          - 410 GONE
          - 411 LENGTH_REQUIRED
          - 412 PRECONDITION_FAILED
          - 413 PAYLOAD_TOO_LARGE
          - 413 REQUEST_ENTITY_TOO_LARGE
          - 414 URI_TOO_LONG
          - 414 REQUEST_URI_TOO_LONG
          - 415 UNSUPPORTED_MEDIA_TYPE
          - 416 REQUESTED_RANGE_NOT_SATISFIABLE
          - 417 EXPECTATION_FAILED
          - 418 I_AM_A_TEAPOT
          - 419 INSUFFICIENT_SPACE_ON_RESOURCE
          - 420 METHOD_FAILURE
          - 421 DESTINATION_LOCKED
          - 422 UNPROCESSABLE_ENTITY
          - 423 LOCKED
          - 424 FAILED_DEPENDENCY
          - 425 TOO_EARLY
          - 426 UPGRADE_REQUIRED
          - 428 PRECONDITION_REQUIRED
          - 429 TOO_MANY_REQUESTS
          - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
          - 451 UNAVAILABLE_FOR_LEGAL_REASONS
          - 500 INTERNAL_SERVER_ERROR
          - 501 NOT_IMPLEMENTED
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          - 504 GATEWAY_TIMEOUT
          - 505 HTTP_VERSION_NOT_SUPPORTED
          - 506 VARIANT_ALSO_NEGOTIATES
          - 507 INSUFFICIENT_STORAGE
          - 508 LOOP_DETECTED
          - 509 BANDWIDTH_LIMIT_EXCEEDED
          - 510 NOT_EXTENDED
          - 511 NETWORK_AUTHENTICATION_REQUIRED
        timestamp:
          type: string
          description: Response time
          format: date-time
        data:
          type: object
          description: Response data
    ApiAcceptedResponse:
      type: object
      properties:
        code:
          type: integer
          description: Http status code
          format: int32
          example: 202
        message:
          type: string
          description: Message
          example: Request already in Progress.
        status:
          type: string
          description: Http status
          example: Accepted
          enum:
          - 100 CONTINUE
          - 101 SWITCHING_PROTOCOLS
          - 102 PROCESSING
          - 103 CHECKPOINT
          - 200 OK
          - 201 CREATED
          - 202 ACCEPTED
          - 203 NON_AUTHORITATIVE_INFORMATION
          - 204 NO_CONTENT
          - 205 RESET_CONTENT
          - 206 PARTIAL_CONTENT
          - 207 MULTI_STATUS
          - 208 ALREADY_REPORTED
          - 226 IM_USED
          - 300 MULTIPLE_CHOICES
          - 301 MOVED_PERMANENTLY
          - 302 FOUND
          - 302 MOVED_TEMPORARILY
          - 303 SEE_OTHER
          - 304 NOT_MODIFIED
          - 305 USE_PROXY
          - 307 TEMPORARY_REDIRECT
          - 308 PERMANENT_REDIRECT
          - 400 BAD_REQUEST
          - 401 UNAUTHORIZED
          - 402 PAYMENT_REQUIRED
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 405 METHOD_NOT_ALLOWED
          - 406 NOT_ACCEPTABLE
          - 407 PROXY_AUTHENTICATION_REQUIRED
          - 408 REQUEST_TIMEOUT
          - 409 CONFLICT
          - 410 GONE
          - 411 LENGTH_REQUIRED
          - 412 PRECONDITION_FAILED
          - 413 PAYLOAD_TOO_LARGE
          - 413 REQUEST_ENTITY_TOO_LARGE
          - 414 URI_TOO_LONG
          - 414 REQUEST_URI_TOO_LONG
          - 415 UNSUPPORTED_MEDIA_TYPE
          - 416 REQUESTED_RANGE_NOT_SATISFIABLE
          - 417 EXPECTATION_FAILED
          - 418 I_AM_A_TEAPOT
          - 419 INSUFFICIENT_SPACE_ON_RESOURCE
          - 420 METHOD_FAILURE
          - 421 DESTINATION_LOCKED
          - 422 UNPROCESSABLE_ENTITY
          - 423 LOCKED
          - 424 FAILED_DEPENDENCY
          - 425 TOO_EARLY
          - 426 UPGRADE_REQUIRED
          - 428 PRECONDITION_REQUIRED
          - 429 TOO_MANY_REQUESTS
          - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
          - 451 UNAVAILABLE_FOR_LEGAL_REASONS
          - 500 INTERNAL_SERVER_ERROR
          - 501 NOT_IMPLEMENTED
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          - 504 GATEWAY_TIMEOUT
          - 505 HTTP_VERSION_NOT_SUPPORTED
          - 506 VARIANT_ALSO_NEGOTIATES
          - 507 INSUFFICIENT_STORAGE
          - 508 LOOP_DETECTED
          - 509 BANDWIDTH_LIMIT_EXCEEDED
          - 510 NOT_EXTENDED
          - 511 NETWORK_AUTHENTICATION_REQUIRED
        timestamp:
          type: string
          description: Response time
          format: date-time
        data:
          type: object
          description: Response data
    PageCampaignResponse:
      type: object
      properties:
        totalPages:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int64
        size:
          type: integer
          format: int32
        content:
          type: array
          items:
            $ref: '#/components/schemas/CampaignResponse'
        number:
          type: integer
          format: int32
        sort:
          $ref: '#/components/schemas/Sort'
        first:
          type: boolean
        last:
          type: boolean
        numberOfElements:
          type: integer
          format: int32
        pageable:
          $ref: '#/components/schemas/PageableObject'
        empty:
          type: boolean
      description: Response data
    PageableObject:
      type: object
      properties:
        offset:
          type: integer
          format: int64
        sort:
          $ref: '#/components/schemas/Sort'
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        paged:
          type: boolean
        unpaged:
          type: boolean
    CampaignResponse:
      type: object
      properties:
        campaignId:
          type: string
        status:
          type: string
        brandId:
          type: string
        customerActorId:
          type: string
        cspId:
          type: string
        policy:
          type: string
        useCase:
          type: string
        subUseCase:
          type: string
        msgServiceType:
          type: string
        insertedTime:
          type: string
        updatedTime:
          type: string
        firstDeployedTime:
          type: string
        applicationAddresses:
          type: array
          items:
            type: string
      description: Response data
    ApiOkCampaignResponseExample:
      type: object
      properties:
        code:
          type: integer
          description: Http status code
          format: int32
          example: 200
        message:
          type: string
          description: Message
          example: Request received
        status:
          type: string
          description: Http status
          example: Ok
          enum:
          - 100 CONTINUE
          - 101 SWITCHING_PROTOCOLS
          - 102 PROCESSING
          - 103 CHECKPOINT
          - 200 OK
          - 201 CREATED
          - 202 ACCEPTED
          - 203 NON_AUTHORITATIVE_INFORMATION
          - 204 NO_CONTENT
          - 205 RESET_CONTENT
          - 206 PARTIAL_CONTENT
          - 207 MULTI_STATUS
          - 208 ALREADY_REPORTED
          - 226 IM_USED
          - 300 MULTIPLE_CHOICES
          - 301 MOVED_PERMANENTLY
          - 302 FOUND
          - 302 MOVED_TEMPORARILY
          - 303 SEE_OTHER
          - 304 NOT_MODIFIED
          - 305 USE_PROXY
          - 307 TEMPORARY_REDIRECT
          - 308 PERMANENT_REDIRECT
          - 400 BAD_REQUEST
          - 401 UNAUTHORIZED
          - 402 PAYMENT_REQUIRED
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 405 METHOD_NOT_ALLOWED
          - 406 NOT_ACCEPTABLE
          - 407 PROXY_AUTHENTICATION_REQUIRED
          - 408 REQUEST_TIMEOUT
          - 409 CONFLICT
          - 410 GONE
          - 411 LENGTH_REQUIRED
          - 412 PRECONDITION_FAILED
          - 413 PAYLOAD_TOO_LARGE
          - 413 REQUEST_ENTITY_TOO_LARGE
          - 414 URI_TOO_LONG
          - 414 REQUEST_URI_TOO_LONG
          - 415 UNSUPPORTED_MEDIA_TYPE
          - 416 REQUESTED_RANGE_NOT_SATISFIABLE
          - 417 EXPECTATION_FAILED
          - 418 I_AM_A_TEAPOT
          - 419 INSUFFICIENT_SPACE_ON_RESOURCE
          - 420 METHOD_FAILURE
          - 421 DESTINATION_LOCKED
          - 422 UNPROCESSABLE_ENTITY
          - 423 LOCKED
          - 424 FAILED_DEPENDENCY
          - 425 TOO_EARLY
          - 426 UPGRADE_REQUIRED
          - 428 PRECONDITION_REQUIRED
          - 429 TOO_MANY_REQUESTS
          - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
          - 451 UNAVAILABLE_FOR_LEGAL_REASONS
          - 500 INTERNAL_SERVER_ERROR
          - 501 NOT_IMPLEMENTED
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          - 504 GATEWAY_TIMEOUT
          - 505 HTTP_VERSION_NOT_SUPPORTED
          - 506 VARIANT_ALSO_NEGOTIATES
          - 507 INSUFFICIENT_STORAGE
          - 508 LOOP_DETECTED
          - 509 BANDWIDTH_LIMIT_EXCEEDED
          - 510 NOT_EXTENDED
          - 511 NETWORK_AUTHENTICATION_REQUIRED
        timestamp:
          type: string
          description: Response time
          format: date-time
        data:
          $ref: '#/components/schemas/CampaignResponse'
    ApiInternalErrorResponse:
      type: object
      properties:
        code:
          type: integer
          description: Http status code
          format: int32
          example: 500
        message:
          type: string
          description: Message
          example: Internal Error Occurred
        status:
          type: string
          description: Http status
          example: Internal Server Error
          enum:
          - 100 CONTINUE
          - 101 SWITCHING_PROTOCOLS
          - 102 PROCESSING
          - 103 CHECKPOINT
          - 200 OK
          - 201 CREATED
          - 202 ACCEPTED
          - 203 NON_AUTHORITATIVE_INFORMATION
          - 204 NO_CONTENT
          - 205 RESET_CONTENT
          - 206 PARTIAL_CONTENT
          - 207 MULTI_STATUS
          - 208 ALREADY_REPORTED
          - 226 IM_USED
          - 300 MULTIPLE_CHOICES
          - 301 MOVED_PERMANENTLY
          - 302 FOUND
          - 302 MOVED_TEMPORARILY
          - 303 SEE_OTHER
          - 304 NOT_MODIFIED
          - 305 USE_PROXY
          - 307 TEMPORARY_REDIRECT
          - 308 PERMANENT_REDIRECT
          - 400 BAD_REQUEST
          - 401 UNAUTHORIZED
          - 402 PAYMENT_REQUIRED
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 405 METHOD_NOT_ALLOWED
          - 406 NOT_ACCEPTABLE
          - 407 PROXY_AUTHENTICATION_REQUIRED
          - 408 REQUEST_TIMEOUT
          - 409 CONFLICT
          - 410 GONE
          - 411 LENGTH_REQUIRED
          - 412 PRECONDITION_FAILED
          - 413 PAYLOAD_TOO_LARGE
          - 413 REQUEST_ENTITY_TOO_LARGE
          - 414 URI_TOO_LONG
          - 414 REQUEST_URI_TOO_LONG
          - 415 UNSUPPORTED_MEDIA_TYPE
          - 416 REQUESTED_RANGE_NOT_SATISFIABLE
          - 417 EXPECTATION_FAILED
          - 418 I_AM_A_TEAPOT
          - 419 INSUFFICIENT_SPACE_ON_RESOURCE
          - 420 METHOD_FAILURE
          - 421 DESTINATION_LOCKED
          - 422 UNPROCESSABLE_ENTITY
          - 423 LOCKED
          - 424 FAILED_DEPENDENCY
          - 425 TOO_EARLY
          - 426 UPGRADE_REQUIRED
          - 428 PRECONDITION_REQUIRED
          - 429 TOO_MANY_REQUESTS
          - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
          - 451 UNAVAILABLE_FOR_LEGAL_REASONS
          - 500 INTERNAL_SERVER_ERROR
          - 501 NOT_IMPLEMENTED
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          - 504 GATEWAY_TIMEOUT
          - 505 HTTP_VERSION_NOT_SUPPORTED
          - 506 VARIANT_ALSO_NEGOTIATES
          - 507 INSUFFICIENT_STORAGE
          - 508 LOOP_DETECTED
          - 509 BANDWIDTH_LIMIT_EXCEEDED
          - 510 NOT_EXTENDED
          - 511 NETWORK_AUTHENTICATION_REQUIRED
        timestamp:
          type: string
          description: Response time
          format: date-time
        data:
          type: object
          description: Response data
    ApiGeneralResponse:
      type: object
      properties:
        code:
          type: integer
          description: Http status code
          format: int32
          example: 200
        message:
          type: string
          description: Message
          example: Request received
        status:
          type: string
          description: Http status
          example: OK
          enum:
          - 100 CONTINUE
          - 101 SWITCHING_PROTOCOLS
          - 102 PROCESSING
          - 103 CHECKPOINT
          - 200 OK
          - 201 CREATED
          - 202 ACCEPTED
          - 203 NON_AUTHORITATIVE_INFORMATION
          - 204 NO_CONTENT
          - 205 RESET_CONTENT
          - 206 PARTIAL_CONTENT
          - 207 MULTI_STATUS
          - 208 ALREADY_REPORTED
          - 226 IM_USED
          - 300 MULTIPLE_CHOICES
          - 301 MOVED_PERMANENTLY
          - 302 FOUND
          - 302 MOVED_TEMPORARILY
          - 303 SEE_OTHER
          - 304 NOT_MODIFIED
          - 305 USE_PROXY
          - 307 TEMPORARY_REDIRECT
          - 308 PERMANENT_REDIRECT
          - 400 BAD_REQUEST
          - 401 UNAUTHORIZED
          - 402 PAYMENT_REQUIRED
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 405 METHOD_NOT_ALLOWED
          - 406 NOT_ACCEPTABLE
          - 407 PROXY_AUTHENTICATION_REQUIRED
          - 408 REQUEST_TIMEOUT
          - 409 CONFLICT
          - 410 GONE
          - 411 LENGTH_REQUIRED
          - 412 PRECONDITION_FAILED
          - 413 PAYLOAD_TOO_LARGE
          - 413 REQUEST_ENTITY_TOO_LARGE
          - 414 URI_TOO_LONG
          - 414 REQUEST_URI_TOO_LONG
          - 415 UNSUPPORTED_MEDIA_TYPE
          - 416 REQUESTED_RANGE_NOT_SATISFIABLE
          - 417 EXPECTATION_FAILED
          - 418 I_AM_A_TEAPOT
          - 419 INSUFFICIENT_SPACE_ON_RESOURCE
          - 420 METHOD_FAILURE
          - 421 DESTINATION_LOCKED
          - 422 UNPROCESSABLE_ENTITY
          - 423 LOCKED
          - 424 FAILED_DEPENDENCY
          - 425 TOO_EARLY
          - 426 UPGRADE_REQUIRED
          - 428 PRECONDITION_REQUIRED
          - 429 TOO_MANY_REQUESTS
          - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
          - 451 UNAVAILABLE_FOR_LEGAL_REASONS
          - 500 INTERNAL_SERVER_ERROR
          - 501 NOT_IMPLEMENTED
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          - 504 GATEWAY_TIMEOUT
          - 505 HTTP_VERSION_NOT_SUPPORTED
          - 506 VARIANT_ALSO_NEGOTIATES
          - 507 INSUFFICIENT_STORAGE
          - 508 LOOP_DETECTED
          - 509 BANDWIDTH_LIMIT_EXCEEDED
          - 510 NOT_EXTENDED
          - 511 NETWORK_AUTHENTICATION_REQUIRED
        timestamp:
          type: string
          description: Response time
          format: date-time
        data:
          type: object
          description: Response data
    ApiUnauthorizedResponse:
      type: object
      properties:
        code:
          type: integer
          description: Http status code
          format: int32
          example: 401
        message:
          type: string
          description: Message
          example: You are not authorized to view the resource
        status:
          type: string
          description: Http status
          example: Unauthorized
          enum:
          - 100 CONTINUE
          - 101 SWITCHING_PROTOCOLS
          - 102 PROCESSING
          - 103 CHECKPOINT
          - 200 OK
          - 201 CREATED
          - 202 ACCEPTED
          - 203 NON_AUTHORITATIVE_INFORMATION
          - 204 NO_CONTENT
          - 205 RESET_CONTENT
          - 206 PARTIAL_CONTENT
          - 207 MULTI_STATUS
          - 208 ALREADY_REPORTED
          - 226 IM_USED
          - 300 MULTIPLE_CHOICES
          - 301 MOVED_PERMANENTLY
          - 302 FOUND
          - 302 MOVED_TEMPORARILY
          - 303 SEE_OTHER
          - 304 NOT_MODIFIED
          - 305 USE_PROXY
          - 307 TEMPORARY_REDIRECT
          - 308 PERMANENT_REDIRECT
          - 400 BAD_REQUEST
          - 401 UNAUTHORIZED
          - 402 PAYMENT_REQUIRED
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 405 METHOD_NOT_ALLOWED
          - 406 NOT_ACCEPTABLE
          - 407 PROXY_AUTHENTICATION_REQUIRED
          - 408 REQUEST_TIMEOUT
          - 409 CONFLICT
          - 410 GONE
          - 411 LENGTH_REQUIRED
          - 412 PRECONDITION_FAILED
          - 413 PAYLOAD_TOO_LARGE
          - 413 REQUEST_ENTITY_TOO_LARGE
          - 414 URI_TOO_LONG
          - 414 REQUEST_URI_TOO_LONG
          - 415 UNSUPPORTED_MEDIA_TYPE
          - 416 REQUESTED_RANGE_NOT_SATISFIABLE
          - 417 EXPECTATION_FAILED
          - 418 I_AM_A_TEAPOT
          - 419 INSUFFICIENT_SPACE_ON_RESOURCE
          - 420 METHOD_FAILURE
          - 421 DESTINATION_LOCKED
          - 422 UNPROCESSABLE_ENTITY
          - 423 LOCKED
          - 424 FAILED_DEPENDENCY
          - 425 TOO_EARLY
          - 426 UPGRADE_REQUIRED
          - 428 PRECONDITION_REQUIRED
          - 429 TOO_MANY_REQUESTS
          - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
          - 451 UNAVAILABLE_FOR_LEGAL_REASONS
          - 500 INTERNAL_SERVER_ERROR
          - 501 NOT_IMPLEMENTED
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          - 504 GATEWAY_TIMEOUT
          - 505 HTTP_VERSION_NOT_SUPPORTED
          - 506 VARIANT_ALSO_NEGOTIATES
          - 507 INSUFFICIENT_STORAGE
          - 508 LOOP_DETECTED
          - 509 BANDWIDTH_LIMIT_EXCEEDED
          - 510 NOT_EXTENDED
          - 511 NETWORK_AUTHENTICATION_REQUIRED
        timestamp:
          type: string
          description: Response time
          format: date-time
        data:
          type: object
          description: Response data
    ApiProcessedAlreadyResponse:
      type: object
      properties:
        code:
          type: integer
          description: Http status code
          format: int32
          example: 409
        message:
          type: string
          description: Message
          example: Request already completed.
        status:
          type: string
          description: Http status
          example: Conflict
          enum:
          - 100 CONTINUE
          - 101 SWITCHING_PROTOCOLS
          - 102 PROCESSING
          - 103 CHECKPOINT
          - 200 OK
          - 201 CREATED
          - 202 ACCEPTED
          - 203 NON_AUTHORITATIVE_INFORMATION
          - 204 NO_CONTENT
          - 205 RESET_CONTENT
          - 206 PARTIAL_CONTENT
          - 207 MULTI_STATUS
          - 208 ALREADY_REPORTED
          - 226 IM_USED
          - 300 MULTIPLE_CHOICES
          - 301 MOVED_PERMANENTLY
          - 302 FOUND
          - 302 MOVED_TEMPORARILY
          - 303 SEE_OTHER
          - 304 NOT_MODIFIED
          - 305 USE_PROXY
          - 307 TEMPORARY_REDIRECT
          - 308 PERMANENT_REDIRECT
          - 400 BAD_REQUEST
          - 401 UNAUTHORIZED
          - 402 PAYMENT_REQUIRED
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 405 METHOD_NOT_ALLOWED
          - 406 NOT_ACCEPTABLE
          - 407 PROXY_AUTHENTICATION_REQUIRED
          - 408 REQUEST_TIMEOUT
          - 409 CONFLICT
          - 410 GONE
          - 411 LENGTH_REQUIRED
          - 412 PRECONDITION_FAILED
          - 413 PAYLOAD_TOO_LARGE
          - 413 REQUEST_ENTITY_TOO_LARGE
          - 414 URI_TOO_LONG
          - 414 REQUEST_URI_TOO_LONG
          - 415 UNSUPPORTED_MEDIA_TYPE
          - 416 REQUESTED_RANGE_NOT_SATISFIABLE
          - 417 EXPECTATION_FAILED
          - 418 I_AM_A_TEAPOT
          - 419 INSUFFICIENT_SPACE_ON_RESOURCE
          - 420 METHOD_FAILURE
          - 421 DESTINATION_LOCKED
          - 422 UNPROCESSABLE_ENTITY
          - 423 LOCKED
          - 424 FAILED_DEPENDENCY
          - 425 TOO_EARLY
          - 426 UPGRADE_REQUIRED
          - 428 PRECONDITION_REQUIRED
          - 429 TOO_MANY_REQUESTS
          - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
          - 451 UNAVAILABLE_FOR_LEGAL_REASONS
          - 500 INTERNAL_SERVER_ERROR
          - 501 NOT_IMPLEMENTED
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          - 504 GATEWAY_TIMEOUT
          - 505 HTTP_VERSION_NOT_SUPPORTED
          - 506 VARIANT_ALSO_NEGOTIATES
          - 507 INSUFFICIENT_STORAGE
          - 508 LOOP_DETECTED
          - 509 BANDWIDTH_LIMIT_EXCEEDED
          - 510 NOT_EXTENDED
          - 511 NETWORK_AUTHENTICATION_REQUIRED
        timestamp:
          type: string
          description: Response time
          format: date-time
        data:
          type: object
          description: Response data
    ApiOkPageCampaignResponseExample:
      type: object
      properties:
        code:
          type: integer
          description: Http status code
          format: int32
          example: 200
        message:
          type: string
          description: Message
          example: Request received
        status:
          type: string
          description: Http status
          example: Ok
          enum:
          - 100 CONTINUE
          - 101 SWITCHING_PROTOCOLS
          - 102 PROCESSING
          - 103 CHECKPOINT
          - 200 OK
          - 201 CREATED
          - 202 ACCEPTED
          - 203 NON_AUTHORITATIVE_INFORMATION
          - 204 NO_CONTENT
          - 205 RESET_CONTENT
          - 206 PARTIAL_CONTENT
          - 207 MULTI_STATUS
          - 208 ALREADY_REPORTED
          - 226 IM_USED
          - 300 MULTIPLE_CHOICES
          - 301 MOVED_PERMANENTLY
          - 302 FOUND
          - 302 MOVED_TEMPORARILY
          - 303 SEE_OTHER
          - 304 NOT_MODIFIED
          - 305 USE_PROXY
          - 307 TEMPORARY_REDIRECT
          - 308 PERMANENT_REDIRECT
          - 400 BAD_REQUEST
          - 401 UNAUTHORIZED
          - 402 PAYMENT_REQUIRED
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 405 METHOD_NOT_ALLOWED
          - 406 NOT_ACCEPTABLE
          - 407 PROXY_AUTHENTICATION_REQUIRED
          - 408 REQUEST_TIMEOUT
          - 409 CONFLICT
          - 410 GONE
          - 411 LENGTH_REQUIRED
          - 412 PRECONDITION_FAILED
          - 413 PAYLOAD_TOO_LARGE
          - 413 REQUEST_ENTITY_TOO_LARGE
          - 414 URI_TOO_LONG
          - 414 REQUEST_URI_TOO_LONG
          - 415 UNSUPPORTED_MEDIA_TYPE
          - 416 REQUESTED_RANGE_NOT_SATISFIABLE
          - 417 EXPECTATION_FAILED
          - 418 I_AM_A_TEAPOT
          - 419 INSUFFICIENT_SPACE_ON_RESOURCE
          - 420 METHOD_FAILURE
          - 421 DESTINATION_LOCKED
          - 422 UNPROCESSABLE_ENTITY
          - 423 LOCKED
          - 424 FAILED_DEPENDENCY
          - 425 TOO_EARLY
          - 426 UPGRADE_REQUIRED
          - 428 PRECONDITION_REQUIRED
          - 429 TOO_MANY_REQUESTS
          - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
          - 451 UNAVAILABLE_FOR_LEGAL_REASONS
          - 500 INTERNAL_SERVER_ERROR
          - 501 NOT_IMPLEMENTED
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          - 504 GATEWAY_TIMEOUT
          - 505 HTTP_VERSION_NOT_SUPPORTED
          - 506 VARIANT_ALSO_NEGOTIATES
          - 507 INSUFFICIENT_STORAGE
          - 508 LOOP_DETECTED
          - 509 BANDWIDTH_LIMIT_EXCEEDED
          - 510 NOT_EXTENDED
          - 511 NETWORK_AUTHENTICATION_REQUIRED
        timestamp:
          type: string
          description: Response time
          format: date-time
        data:
          $ref: '#/components/schemas/PageCampaignResponse'
    Sort:
      type: object
      properties:
        empty:
          type: boolean
        unsorted:
          type: boolean
        sorted:
          type: boolean
  securitySchemes:
    SyniverseToken:
      type: http
      scheme: bearer
      bearerFormat: SDC
